// @flow
export default {
  PRODUCTS: 'DATA_REQUEST_PRODUCTS',
  PRODUCTS_SUCCESS: 'DATA_REQUEST_PRODUCTS_SUCCESS',
  PRODUCTS_ERROR: 'DATA_REQUEST_PRODUCTS_ERROR',

  COMMENTS: 'DATA_REQUEST_COMMENTS',
  COMMENTS_SUCCESS: 'DATA_REQUEST_COMMENTS_SUCCESS',
  COMMENTS_ERROR: 'DATA_REQUEST_COMMENTS_ERROR',

  COMMENT_SUBMIT: 'DATA_REQUEST_COMMENT_SUBMIT',
  COMMENT_SUBMIT_SUCCESS: 'DATA_REQUEST_COMMENT_SUBMIT_SUCCESS',
  COMMENT_SUBMIT_ERROR: 'DATA_REQUEST_COMMENT_SUBMIT_ERROR',
};
